In [1]:
import numpy as np

In [2]:
a=np.zeros(5) #return a new array of given shape and type,filled with zeros.


In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
a.ndim

1

In [5]:
b=np.zeros((3,4))

In [6]:
b.ndim

2

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.twos(5)

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.array([[2,2,2],[2,2,2]])

In [ ]:
arr=np.zeros((3,4))

In [ ]:
arr

In [9]:
arr.ndim

NameError: name 'arr' is not defined

In [10]:
#3 dimensional array
np.zeros(1)

array([0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr=np.zeros((3,4))
arr.ndim

2

In [13]:
arr = np.zeros((1,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
 arr.ndim

3

In [15]:
arr = np.zeros((1,1,3,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [16]:
arr.ndim

4

In [17]:
arr = np.zeros((1,1,1,3,4))
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [18]:
arr.ndim

5

In [19]:
arr=np.ones((3,4))

In [20]:
arr.ndim

2

In [21]:
arr.shape

(3, 4)

In [22]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [24]:
a =arr*5

In [25]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [26]:
a-1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [27]:
np.eye(3) #return a 2-D array with ones on the diagonal and zeroes eleswhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3,dtype =int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
np.empty((3,4)) #return a new array of given shape and type, without initializing entries

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [30]:
#optional
import random
random.choice((1,2,3,4,5))

1

In [31]:
random.choice("ajay")

'y'

In [32]:
random.randrange(1,10)

1

In [33]:
random.random() #  a random no is genrated between 0(included) and 1(excluded)

0.5131336721296588

In [34]:
lis =[1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [35]:
random.shuffle(lis)

In [36]:
lis

[5, 4, 2, 1, 3]

In [37]:
random.uniform(7,14)

12.280478058123071

In [38]:
#random number related concept in numpy
np.array([])

array([], dtype=float64)

In [39]:
np.random.random_sample()

0.829743045767958

In [40]:
np.random.random_sample((5, ))

array([0.34931139, 0.6774733 , 0.19841669, 0.88785725, 0.27665139])

In [41]:
np.random.rand(1)

array([0.80863798])

In [42]:
np.random.rand(2,3)

array([[0.74930873, 0.43377323, 0.24899493],
       [0.2207124 , 0.84299141, 0.68461937]])

In [43]:
np.random.randn(2,3)

array([[-0.42070657,  0.26245146, -0.77418794],
       [ 0.53282384,  0.97997083, -0.12567715]])

In [44]:
arr=np.random.randint(1,5, size=(3,4))

In [45]:
arr.ndim

2

In [46]:
arr.shape


(3, 4)

In [47]:
arr.size

12

In [48]:
arr

array([[4, 1, 1, 3],
       [2, 3, 2, 4],
       [4, 4, 3, 4]])

In [49]:
#reshapping the array
arr1=arr.reshape(2,6)

In [50]:
arr1

array([[4, 1, 1, 3, 2, 3],
       [2, 4, 4, 4, 3, 4]])

In [51]:
arr1.size

12

In [52]:
arr

array([[4, 1, 1, 3],
       [2, 3, 2, 4],
       [4, 4, 3, 4]])

In [53]:
arr.size

12

In [54]:
arr

array([[4, 1, 1, 3],
       [2, 3, 2, 4],
       [4, 4, 3, 4]])

In [55]:
#array size will not change , always resape parameter should be multiplication of original array size

In [56]:
arr

array([[4, 1, 1, 3],
       [2, 3, 2, 4],
       [4, 4, 3, 4]])

In [57]:
arr.size

12

In [58]:
arr.reshape(1,12)

array([[4, 1, 1, 3, 2, 3, 2, 4, 4, 4, 3, 4]])

In [59]:
arr.reshape(12,1)

array([[4],
       [1],
       [1],
       [3],
       [2],
       [3],
       [2],
       [4],
       [4],
       [4],
       [3],
       [4]])

In [60]:
arr.reshape(3,4)

array([[4, 1, 1, 3],
       [2, 3, 2, 4],
       [4, 4, 3, 4]])

In [61]:
#case when you dont know is reshape what should be the column count

arr.reshape(4,-1)

array([[4, 1, 1],
       [3, 2, 3],
       [2, 4, 4],
       [4, 3, 4]])

In [62]:
arr.reshape(2,-1)

array([[4, 1, 1, 3, 2, 3],
       [2, 4, 4, 4, 3, 4]])

In [66]:
arr1=arr.reshape(-1,3) #you know count but don't know row count
arr1

array([[4, 1, 1],
       [3, 2, 3],
       [2, 4, 4],
       [4, 3, 4]])

In [67]:
arr1.size

12

In [68]:
arr.reshape(12,1)

array([[4],
       [1],
       [1],
       [3],
       [2],
       [3],
       [2],
       [4],
       [4],
       [4],
       [3],
       [4]])

In [69]:
arr.reshape(12,1).base #to see the original array

array([[4, 1, 1, 3],
       [2, 3, 2, 4],
       [4, 4, 3, 4]])

In [70]:
arr.reshape(2,2,3)

array([[[4, 1, 1],
        [3, 2, 3]],

       [[2, 4, 4],
        [4, 3, 4]]])

In [72]:
arr.reshape(1,2,2,3).ndim

4

In [73]:
arr.reshape(4,3,1) #3rows 1column repetad 4 times in the thired dimensional

array([[[4],
        [1],
        [1]],

       [[3],
        [2],
        [3]],

       [[2],
        [4],
        [4]],

       [[4],
        [3],
        [4]]])

In [76]:
#condition on array

arr1 = np.random.randint(1,10,(5,6))

In [77]:
arr1

array([[9, 6, 5, 8, 2, 8],
       [2, 7, 8, 4, 4, 8],
       [1, 4, 6, 6, 9, 8],
       [4, 9, 5, 3, 5, 4],
       [5, 9, 2, 9, 7, 5]])

In [79]:
arr1.shape

(5, 6)

In [80]:
arr1.ndim

2

In [81]:
arr1.size

30

In [82]:
arr1> 3

array([[ True,  True,  True,  True, False,  True],
       [False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True],
       [ True,  True, False,  True,  True,  True]])

In [84]:
arr1[arr1<3]

array([2, 2, 1, 2])

In [85]:
arr1

array([[9, 6, 5, 8, 2, 8],
       [2, 7, 8, 4, 4, 8],
       [1, 4, 6, 6, 9, 8],
       [4, 9, 5, 3, 5, 4],
       [5, 9, 2, 9, 7, 5]])

In [86]:
#to acess element in the array
arr1[0]

array([9, 6, 5, 8, 2, 8])

In [87]:
arr[1]

array([2, 3, 2, 4])

In [88]:
arr1[1][0]

2

In [89]:
arr1

array([[9, 6, 5, 8, 2, 8],
       [2, 7, 8, 4, 4, 8],
       [1, 4, 6, 6, 9, 8],
       [4, 9, 5, 3, 5, 4],
       [5, 9, 2, 9, 7, 5]])

In [91]:
arr1[0:3] #0th row ,1st row ,2nd row

array([[9, 6, 5, 8, 2, 8],
       [2, 7, 8, 4, 4, 8],
       [1, 4, 6, 6, 9, 8]])

In [92]:
arr1[0:3,[0,2]] # 0th to 2nd and 0th and 2nd column

array([[9, 5],
       [2, 8],
       [1, 6]])

In [93]:
#slicing on both row and column

In [94]:
arr1

array([[9, 6, 5, 8, 2, 8],
       [2, 7, 8, 4, 4, 8],
       [1, 4, 6, 6, 9, 8],
       [4, 9, 5, 3, 5, 4],
       [5, 9, 2, 9, 7, 5]])

In [95]:
arr1[0:3, 1:3]

array([[6, 5],
       [7, 8],
       [4, 6]])

In [96]:
arr1[0:2,[0,1]]

array([[9, 6],
       [2, 7]])

In [97]:
arr1[0,[1,3]]

array([6, 8])

In [98]:
arr1[2:4,[0,3]]

array([[1, 6],
       [4, 3]])

In [99]:
arr1[2:5]

array([[1, 4, 6, 6, 9, 8],
       [4, 9, 5, 3, 5, 4],
       [5, 9, 2, 9, 7, 5]])

In [100]:
arr1[2:5,0:2]

array([[1, 4],
       [4, 9],
       [5, 9]])

In [104]:
#mathematical operation on two arrays
arr1= np.random.randint(1,3,(3,3))
arr2= np.random.randint(1,3,(3,3))


In [105]:
arr1

array([[2, 2, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [106]:
arr2

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [107]:
arr1+arr2 #indx wise addition

array([[4, 3, 2],
       [3, 2, 2],
       [3, 3, 3]])

In [108]:
arr1-arr2 #indx wise subtraction

array([[ 0,  1,  0],
       [-1,  0,  0],
       [-1, -1, -1]])

In [109]:
arr1*arr2 #indx wise multiplication

array([[4, 2, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [110]:
arr1,arr2

(array([[2, 2, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[2, 1, 1],
        [2, 1, 1],
        [2, 2, 2]]))

In [111]:
arr1/arr2 #index wise division

array([[1. , 2. , 1. ],
       [0.5, 1. , 1. ],
       [0.5, 0.5, 0.5]])

In [116]:
4/0

ZeroDivisionError: division by zero

In [ ]:
arr1/0 # in python zero division error will come , but in numpy no error

In [112]:
#matrix multiplication >> different from index wise multiplication

In [114]:
arr1@arr2 # 1st way to matrix multiplication

array([[10,  6,  6],
       [ 6,  4,  4],
       [ 6,  4,  4]])

In [115]:
np.dot(arr1,arr2) #2nd  way to matrix multiplication

array([[10,  6,  6],
       [ 6,  4,  4],
       [ 6,  4,  4]])

In [124]:
#broadcasting
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [125]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [126]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [127]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [128]:
a= np.array([1,2,3,4])

In [129]:
a

array([1, 2, 3, 4])

In [130]:
a.ndim

1

In [131]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [144]:
a= np.array([[1,2,3,4]])

In [145]:
a

array([[1, 2, 3, 4]])

In [146]:
#Transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [147]:
arr1

array([[2, 2, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [148]:
arr1.T

array([[2, 1, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [149]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        ]])

In [150]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     ]])

In [151]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [152]:
np.min(arr1)

1

In [153]:
np.max(arr1)

2