In [2]:
import numpy as np

In [3]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [4]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [5]:
arr1.flatten() #return a copy of the array collapsed into one dimension.

array([2, 1, 1, 2, 1, 1, 2, 1, 2])

In [6]:
#expand dimension
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
arr.ndim

1

In [8]:
np.expand_dims(arr,axis =0) #increases the dimension by 1 at provided axis

array([[1, 2, 3, 4]])

In [9]:
np.expand_dims(arr,axis =1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.expand_dims(arr,axis =0).ndim

2

In [11]:
arr


array([1, 2, 3, 4])

In [12]:
arr=np.zeros((3,4))

In [13]:
arr.ndim

2

In [14]:
np.expand_dims(arr,axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [16]:
np.expand_dims(arr,axis=0).ndim

3

In [17]:
a= np.array([[1], [2], [3]])

In [18]:
a

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(a) #remove axes of length one from 'a'

array([1, 2, 3])

In [20]:
a


array([[1],
       [2],
       [3]])

In [21]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [22]:
np.repeat(arr1,2)

array([2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2])

In [23]:
np.repeat(arr1,2,axis=0)

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [24]:
np.repeat(arr1,3,axis=0)

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [26]:
np.repeat(arr1,3,axis=1)

array([[2, 2, 2, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 2, 2, 2]])

In [27]:
a

array([[1],
       [2],
       [3]])

In [30]:
np.roll(a,-1)

array([[2],
       [3],
       [1]])

In [31]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [33]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [34]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
np.roll(c,-2)

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [37]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [38]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [39]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [40]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [1, 2, 2]])

In [41]:
arr1+arr2

array([[4, 3, 3],
       [3, 3, 2],
       [3, 3, 4]])

In [42]:
arr1-arr2

array([[ 0, -1, -1],
       [ 1, -1,  0],
       [ 1, -1,  0]])

In [43]:
arr1>arr2

array([[False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [45]:
~arr1

array([[-3, -2, -2],
       [-3, -2, -2],
       [-3, -2, -3]])

In [46]:
#operations on numpy string array

In [47]:
d=np.array(["pw","skills"])

In [48]:
d

array(['pw', 'skills'], dtype='<U6')

In [49]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [50]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [51]:
#mathmatical functions

In [52]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [53]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.84147098],
       [0.90929743, 0.84147098, 0.84147098],
       [0.90929743, 0.84147098, 0.90929743]])

In [54]:
np.cos(arr1)

array([[-0.41614684,  0.54030231,  0.54030231],
       [-0.41614684,  0.54030231,  0.54030231],
       [-0.41614684,  0.54030231, -0.41614684]])

In [55]:
np.tan(arr1)

array([[-2.18503986,  1.55740772,  1.55740772],
       [-2.18503986,  1.55740772,  1.55740772],
       [-2.18503986,  1.55740772, -2.18503986]])

In [56]:
np.log(arr1)

array([[0.69314718, 0.        , 0.        ],
       [0.69314718, 0.        , 0.        ],
       [0.69314718, 0.        , 0.69314718]])

In [57]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [58]:
np.mean(arr1)

1.4444444444444444

In [59]:
np.max(arr1)

2

In [60]:
np.min(arr1)

1

In [61]:
np.std(arr1)

0.4969039949999533

In [62]:
np.var(arr1)

0.2469135802469136

In [63]:
arr1-arr2

array([[ 0, -1, -1],
       [ 1, -1,  0],
       [ 1, -1,  0]])

In [64]:
np.subtract(arr1,arr2)

array([[ 0, -1, -1],
       [ 1, -1,  0],
       [ 1, -1,  0]])

In [65]:
arr1*arr2

array([[4, 2, 2],
       [2, 2, 1],
       [2, 2, 4]])

In [66]:
np.multiply(arr1,arr2)

array([[4, 2, 2],
       [2, 2, 1],
       [2, 2, 4]])

In [67]:
np.mod(arr1,arr2) #return elemrnt wise remainder

array([[0, 1, 1],
       [0, 1, 0],
       [0, 1, 0]])

In [68]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [69]:
#sort search

e= np.array([5,6,1,2])

In [70]:
e

array([5, 6, 1, 2])

In [71]:
np.sort(e)

array([1, 2, 5, 6])

In [72]:
f = np.array([5,199,200,6,7,8])

In [73]:
f

array([  5, 199, 200,   6,   7,   8])

In [74]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [75]:
np.searchsorted(f,170) #Find indices where elements should be inserted to maintain order.


6

In [76]:
f = np.array([5,199,200,6,7,0,0,0,8])
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [77]:
np.count_nonzero(f)

6

In [79]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [82]:
np.where(f>0)

(array([0, 1, 2, 3, 4, 8], dtype=int64),)

In [83]:
np.extract(f>0,f)

array([  5, 199, 200,   6,   7,   8])

In [84]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [85]:
f.byteswap()

array([  83886080, -956301312, -939524096,  100663296,  117440512,
                0,          0,          0,  134217728])

In [87]:
#matrix>> 2d array()
import numpy.matlib as nm

In [88]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [89]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
#numpy linear algebra

arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

In [103]:
arr1

array([[7, 8, 6],
       [6, 8, 7],
       [7, 2, 2]])

In [104]:
arr2

array([[3, 9, 3],
       [5, 7, 3],
       [9, 2, 7]])

In [105]:
arr1 @ arr2

array([[115, 131,  87],
       [121, 124,  91],
       [ 49,  81,  41]])

In [106]:
np.linalg.det(arr1)

46.0

In [108]:
np.linalg.inv(arr1)

array([[ 0.04347826, -0.08695652,  0.17391304],
       [ 0.80434783, -0.60869565, -0.2826087 ],
       [-0.95652174,  0.91304348,  0.17391304]])

In [109]:
a = np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [110]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [111]:
b=np.array([16,8,0])

In [112]:
b

array([16,  8,  0])

In [113]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])