In [2]:
#numpy >> numerical python
#2005 by travis oliphant

In [46]:
import numpy as np

In [47]:
np.__version__

'1.26.4'

In [48]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [49]:
lis =[1,2,3,"pwskills",3+5j,True,1.2]

In [50]:
type(lis)

list

In [51]:
lis

[1, 2, 3, 'pwskills', (3+5j), True, 1.2]

In [52]:
#Numpy stores the data in array
#An array is a container used to store the data of same data type 

In [53]:
#why numpy
#computation is fast >> due to array >>> continous memory location
#mathematical computaion

In [54]:
l=[1,2,3,4,5]

In [55]:
arr = np.array(l)

In [56]:
arr

array([1, 2, 3, 4, 5])

In [57]:
l=[1,2,3,4,5.1]
arr = np.array(l)


In [58]:
arr #one change in float autometicaly all convert in float

array([1. , 2. , 3. , 4. , 5.1])

In [59]:
l=[1,2,3,4,5.1,"anmol"]
arr = np.array(l)


In [60]:
arr #one change in string autometicaly all convert in string

array(['1', '2', '3', '4', '5.1', 'anmol'], dtype='<U32')

In [61]:
#arr stores homogenous data

In [62]:
type(arr)

numpy.ndarray

In [63]:
arr.ndim

1

In [64]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [65]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr1.ndim

2

In [24]:
mat = np.matrix([1,2,3,4]) #matrix is aspecial array , 2 dimesional

In [25]:
type(mat)

numpy.matrix

In [26]:
np.matrix([[[1,2,3],[3,4],[5,6]]]) # matrix has only two dimensonal

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 3) + inhomogeneous part.

In [ ]:
#more way to convert array
l = [1,2,3]
np.asarray(l)

In [ ]:
mat

In [ ]:
np.asarray(mat)

In [ ]:
np.asanyarray([1,2,3])

In [27]:
mat

matrix([[1, 2, 3, 4]])

In [28]:
np.asanyarray(mat) #Convert the input to an ndarray, but pass ndarray subclasses through.

matrix([[1, 2, 3, 4]])

In [29]:
t= ([1,2,3],[4,5,6]) #tuple to array

In [30]:
type(t)

tuple

In [31]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
l= [1,2,3,4,5]
abc = np.array(l)

In [33]:
abc

array([1, 2, 3, 4, 5])

In [34]:
abc[0]=500

In [35]:
abc

array([500,   2,   3,   4,   5])

In [36]:
a=abc

In [37]:
a

array([500,   2,   3,   4,   5])

In [38]:
abc[0]=1000

In [39]:
abc

array([1000,    2,    3,    4,    5])

In [40]:
a  #change in array also lead to change in a >> shallow  copy

array([1000,    2,    3,    4,    5])

In [41]:
# To creat an array >> np.array, np.array, np.asarray, np.asanyarray, deep copy and shallow copy

In [42]:
#multiple ways to genrate array

In [66]:
arr1 = np.fromfunction(lambda i, j : i==j, (3,3)) #construct an array by executing a function over each coordinate

In [67]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [68]:
arr1.ndim

2

In [70]:
arr1.shape #shape of array

(3, 3)

In [71]:
arr1.size #no. of elements inarray

9

In [78]:
arr2 = np.fromfunction(lambda i, j : i*j, (3,3))

In [79]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [80]:
for i in range(5):
    print(i)


0
1
2
3
4


In [81]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [82]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [83]:
iterable = (i for i in range(5))

In [85]:
np.fromiter(iterable,int) #creat a new 1-dimensional array from an iterable object.

array([0, 1, 2, 3, 4])

In [86]:
np.fromstring('22 23 24',sep=" ") #value should be numerical

array([22., 23., 24.])

In [89]:
np.fromstring('22,23,24',sep=",")

array([22., 23., 24.])

In [90]:
string = 'ajay,bijay,sanjay'
string1 = string.split(',')
np.array(string1)

array(['ajay', 'bijay', 'sanjay'], dtype='<U6')

In [91]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
range(10)

range(0, 10)

In [93]:
#other methods of numpy >> to generate sequence of nos
np.arange(1,10,0.1) #Return evenly spaced values within a given interval.

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [94]:
np.linspace(1,5,10) #return evenly spaced numbers over a specified interval.
#given me 10 numbers between 1 and 5 evenly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [95]:
np.logspace(1,5,10) # return numbers spaced evenly on a log scale, base is 10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [96]:
np.logspace(1,5,10, base = 2) 

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])